### ISSUE TITLE
function to normalize zip codes

### ISSUE THREAD

**Issue by clauswilke** [gavinrozzi/zipcodeR#10]
Would it be in scope to add a function that can take all sorts of messed-up input and normalize into standard five-character zip codes?

I have written such a function here. Feel free to copy over:
https://github.com/clauswilke/zipcodes/blob/main/normalize_zip.Rmd

**Comment by gavinrozzi** [comment]
That would definitely be in scope, and very helpful! I will copy it over. Thanks!

**Comment by gavinrozzi** [comment]
Added this to the develop branch in 08d16ef98f788bc646b8f300983633262410fdd0 so I'm closing this issue.
