### ISSUE TITLE
Missing Zip codes

### ISSUE THREAD

**Issue by Stephonomon** [gavinrozzi/zipcodeR#12]
I was validating your zips by joining your database with our membership director. I saw that a zip like this is not found.

reverse_zipcode('72304')

https://www.zipdatamaps.com/72034

**Comment by gavinrozzi** [comment]
Thanks for your issue. The package currently relies on an upstream open-source database for zip_code_db. I don’t currently have plans to change this so this missing zip code cannot be addressed at this time. This may be something I will revisit in the future.
