### ISSUE TITLE
Missing zipcode

### ISSUE THREAD

**Issue by lmathew78** [gavinrozzi/zipcodeR#15]
Hello,
Thank you for the excellent package! I was trying to use the geocode_zip function to get the lat and long values for zipcodes in my data. The function does not return (NA) the lat and long values for zipcode 29652. Is this an omission in the files that can be changed?

Thanks!

**Comment by gavinrozzi** [comment]
Thanks for your issue. The package currently relies on an upstream open-source database for zip_code_db. I don’t currently have plans to change this so this missing zip code cannot be addressed at this time. This may be something I will revisit in the future.
