### ISSUE TITLE
ZipcodeR  crashes macbook with ARM64

### ISSUE THREAD

**Issue by priessdev** [gavinrozzi/zipcodeR#16]
Hi - I tried  2x to install ZipcodeR including both from github and CRAN  and there appears to be issues.  When I installed from CRAN, when I go to library the package,  it crashes my Rstudio session.  

When I tried to install from the github dev version, it crashes and will not install... error below

tools:::makeLazyLoading("zipcodeR", "/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/00LOCK-zipcodeR/00new",     keep.source = FALSE, keep.parse.data = FALSE, set.install.dir = "/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/zipcodeR")
An irrecoverable exception occurred. R is aborting now ...

Any thoughts?

**Comment by seth-cp** [comment]
I am having the same issue. I can successfully install zipcodeR. I also tried installing the two previous versions from GitHub. Though they all installed successfully, as soon as I type `zipcodeR::` into the R console in RStudio, the session crashes, before I even hit enter!

@priessdev I see you closed this issue, did you resolve it?
