### ISSUE TITLE
plot_usmap doesn't like "values"

### ISSUE THREAD

**Issue by mnr** [gavinrozzi/zipcodeR#17]
plot_usmap gets confused by a column named "values"

# Assume a data.frame as follows...
> str(myDF)
$ fips : Factor w/ 30 levels ...
$ values : int ...

> plot_usmap(data = myDF)
Error in `[.data.frame`(map_df, , values) : undefined columns selected

# this also fails...
> plot_usmap(data = myDF, values = "values" )
Error in `[.data.frame`(map_df, , values) : undefined columns selected

# BUT...this works...
> str(myDF)
$ fips : Factor w/ 30 levels ...
$ population : int ...

> plot_usmap(data = myDF, values = "population" )
# which produces the expected plot

**Comment by gavinrozzi** [comment]
Thanks, @mnr. Could you please post the code that raised this error as a reprex? https://reprex.tidyverse.org
I'd like to try and reproduce this on my end for troubleshooting. Thanks.

**Comment by mnr** [comment]
Oh crap. I'm an idiot. plot_usmap is part of usmap - NOT zipcoder. My apologies. These are not the droids you are looking for. Move along...
