### ISSUE TITLE
dplyr and stringr dependency suboptimal in DESCRIPTION

### ISSUE THREAD

**Issue by clauswilke** [gavinrozzi/zipcodeR#8]
Currently, both dplyr and stringr are listed under `Depends` in the DESCRIPTION file:
https://github.com/gavinrozzi/zipcodeR/blob/7b60ec57777fe7438adbb5403722711236e92a3a/DESCRIPTION#L21-L24

This will cause them to get attached to the user session when zipcodeR is loaded. See e.g. here:
``` r
library(zipcodeR)
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> Loading required package: stringr
```

<sup>Created on 2021-04-04 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

This use is generally discouraged. Always create dependencies via `Imports` if at all possible.

See here for details: https://r-pkgs.org/namespace.html

**Comment by gavinrozzi** [comment]
Thanks for point that out. This has been addressed in 58cdddff28cb11a967f014dabcb6b831790e5dba so I'll be closing this issue.
