### ISSUE TITLE
reverse_zipcode() needs a quiet option

### ISSUE THREAD

**Issue by clauswilke** [gavinrozzi/zipcodeR#9]
The function `reverse_zipcode()` always writes output to stdout. That's impolite. It makes it very difficult to use this function in a program and control what the program does and doesn't write to stdout. Usually, functions in R have a `quiet` option that turns off this type of output.

Reprex:
``` r
library(zipcodeR)
#> Loading required package: dplyr
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
#> Loading required package: stringr

# this should not generate any output,
# or at least there should be an option to turn output off
zip_data <- reverse_zipcode("22311")
#> 1 row of data found for ZIP code: '22311'
```

<sup>Created on 2021-04-04 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by gavinrozzi** [comment]
Thanks - this has been addressed with the new 0.3 release on CRAN today, and all functions are set to run quietly by default, here is the new output reprex:

``` r
library(zipcodeR)
zip_data <- reverse_zipcode("22311")
```

<sup>Created on 2021-04-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
